#!/bin/bash
# FORGE Pre-Compact Hook
# Saves critical context before session compaction

set -e

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
MEMORY_DIR="${PLUGIN_ROOT}/.claude/memory"
DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "🔧 FORGE: Running pre-compact hook..."

# Create memory directory if it doesn't exist
mkdir -p "${MEMORY_DIR}/session-snapshots"
mkdir -p "${MEMORY_DIR}/.insights_pending"

# Check context level - if at 5% or below, create insights pending marker
# Note: Context level detection happens via the hook framework

# Save session context for next session
cat > "${MEMORY_DIR}/last_session_context.md" << EOF
---
session_end: ${DATE}
context_remaining: triggered
---

# Last Session Summary

Session ended at ${DATE}.

## Context Preservation

Critical information has been saved to:
- Memory graph: ${MEMORY_DIR}/graph/memory.json
- Entities: ${MEMORY_DIR}/entities/
- Patterns: ${MEMORY_DIR}/patterns/
- Learnings: ${MEMORY_DIR}/learnings/

## Next Session Actions

1. Run \`/forge:learn\` to process any pending insights
2. Run \`/forge:status\` to see project state
3. Use \`@skill-router\` to auto-route new tasks

---
*Auto-generated by FORGE Pre-Compact Hook*
EOF

# Create insights pending marker
if [ ! -f "${MEMORY_DIR}/.insights_pending/active" ]; then
  mkdir -p "${MEMORY_DIR}/.insights_pending"
  echo "${DATE}" > "${MEMORY_DIR}/.insights_pending/active"
  echo "📊 Insights marker created for next session"
fi

echo "✅ Pre-compact hook complete"
